### ISSUE TITLE
M1 Mac 无法激活扩展

### ISSUE THREAD

**Issue by zhhanging** [YXL76/cloudmusic-vscode#414]
**Describe the bug**
Mac 无法激活扩展

**Error information (Help->Toggle Developer Tools->Console)**
<img width="556" alt="CleanShot 2021-04-28 at 15 27 20@2x" src="https://user-images.githubusercontent.com/39266588/116363941-3f61b380-a836-11eb-8ac3-016fd9201e89.png">

**Environment (Help->About)**
版本: 1.55.2 (Universal)
提交: 3c4e3df9e89829dce27b7b5c24508306b151f30d
日期: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.4.0

**Comment by YXL76** [comment]
m1的机器吗

**Comment by zhhanging** [comment]
是的，m1 的 MacBook Air
在 environments信息中显示为 OS: Darwin arm64 20.4.0


2021年4月28日 下午3:33，兰陈昕 ***@***.******@***.***>> 写道：



m1的机器吗

**Comment by zhhanging** [comment]
是的，是 M1 MacBook Air

**Comment by YXL76** [comment]
现在暂时不支持，近期将发布的新版本应该能支持

**Comment by YXL76** [comment]
根据[Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)，Github action的macOS 11.0还在测试中，欢迎有rust环境的用户帮忙编译本机模块

**Comment by hzfmer** [comment]
@YXL76  不知道是不是一个问题，我也遇到了无法打开的问题：
M1, Big Sur, 11.3.1

```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:12.490Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.4.0
```

```
console.ts:137 [Extension Host] (node:36759) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
m @ console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command 'extension.js-debug.clearAutoAttachVariables' not found
m @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: command 'extension.js-debug.clearAutoAttachVariables' not found    at g._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3360)    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3241    at processTicksAndRejections (internal/process/task_queues.js:93:5)
m @ console.ts:137
log.ts:296   ERR command 'extension.js-debug.clearAutoAttachVariables' not found: Error: command 'extension.js-debug.clearAutoAttachVariables' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3360)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
log.ts:296   ERR connect ENOENT /tmp/cm-vscserver: Error: connect ENOENT /tmp/cm-vscserver
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscbc-server: Error: connect ENOENT /tmp/cm-vscbc-server
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscserver: Error: connect ENOENT /tmp/cm-vscserver
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscbc-server: Error: connect ENOENT /tmp/cm-vscbc-server
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscserver: Error: connect ENOENT /tmp/cm-vscserver
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscbc-server: Error: connect ENOENT /tmp/cm-vscbc-server
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscserver: Error: connect ENOENT /tmp/cm-vscserver
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
log.ts:296   ERR connect ENOENT /tmp/cm-vscbc-server: Error: connect ENOENT /tmp/cm-vscbc-server
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

有空的话希望可以看一下，谢谢！

**Comment by YXL76** [comment]
从`v9.0.0`起，不支持的平台会自动降级到`wasm`，理论上可以使用了。等 Github Actions 放出 macOS 11 后会添加本机模块的支持。

**Comment by YXL76** [comment]
已在`v9.2.1`中支持本机模块
