### ISSUE TITLE
在Code1.57.0与8.3.4上无法登录

### ISSUE THREAD

**Issue by GysdfHome** [YXL76/cloudmusic-vscode#472]
如标题
另外，二维码登录无法使用

err.log头
```
  19      1623551721806 Error: unable to verify the first certificate
  18   ┊ at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
  17   ┊ at TLSSocket.emit (events.js:315:20)
  16   ┊ at TLSSocket._finishInit (_tls_wrap.js:932:8)
  15   ┊ at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  14      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
```

**Comment by GysdfHome** [comment]
经查证是路由器unlock插件的问题
