### ISSUE TITLE
无法搜索 使其他功能失效

### ISSUE THREAD

**Issue by Tim-Fang** [YXL76/cloudmusic-vscode#504]
**Describe the bug**
当我打开搜索,输入歌曲名后(此时没有显示联想建议)并按下换行后,窗口消失,账户菜单中其它按钮失效
操作:  
- 激活拓展
- 点击底部栏账户图标
- 打开搜索
- 输入歌曲名
- 换行
- 窗口消失
- 再次点击账户图标
- 所有按钮不可用

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容
```
[Extension Host] TypeError: Cannot read property 'label' of undefined	at bh (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\extension.js:69:27070)	at processTicksAndRejections (internal/process/task_queues.js:93:5)	at async we.stepThrough (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\extension.js:38:10158)
m @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1704
_doInvokeHandler @ workbench.desktop.main.js:1704
_invokeHandler @ workbench.desktop.main.js:1704
_receiveRequest @ workbench.desktop.main.js:1704
_receiveOneMessage @ workbench.desktop.main.js:1704
(anonymous) @ workbench.desktop.main.js:1704
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2844
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```
```
Access to XMLHttpRequest at 'https://yxl.gallerycdn.azure.cn/extensions/yxl/cloudmusic/8.3.9/1625653972145/Microsoft.VisualStudio.Services.Content.Details' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
workbench.desktop.main.js:76 GET https://yxl.gallerycdn.azure.cn/extensions/yxl/cloudmusic/8.3.9/1625653972145/Microsoft.VisualStudio.Services.Content.Details net::ERR_FAILED
(anonymous) @ workbench.desktop.main.js:76
A @ workbench.desktop.main.js:76
request @ workbench.desktop.main.js:634
getAsset @ workbench.desktop.main.js:639
async function (async)
getAsset @ workbench.desktop.main.js:639
getReadme @ workbench.desktop.main.js:639
getReadme @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2773
y @ workbench.desktop.main.js:68
(anonymous) @ workbench.desktop.main.js:2773
get @ workbench.desktop.main.js:60
openReadme @ workbench.desktop.main.js:2834
async function (async)
openReadme @ workbench.desktop.main.js:2834
open @ workbench.desktop.main.js:2773
onNavbarChange @ workbench.desktop.main.js:2773
updateTemplate @ workbench.desktop.main.js:2773
async function (async)
updateTemplate @ workbench.desktop.main.js:2773
setInput @ workbench.desktop.main.js:2773
async function (async)
setInput @ workbench.desktop.main.js:2773
doSetInput @ workbench.desktop.main.js:2355
openEditor @ workbench.desktop.main.js:2355
(anonymous) @ workbench.desktop.main.js:2567
doShowEditor @ workbench.desktop.main.js:2567
openEditor @ workbench.desktop.main.js:2567
openEditor @ workbench.desktop.main.js:2405
async function (async)
openEditor @ workbench.desktop.main.js:2405
open @ workbench.desktop.main.js:2839
openExtension @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:58
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:58
fire @ workbench.desktop.main.js:60
_open @ workbench.desktop.main.js:662
onPointer @ workbench.desktop.main.js:662
(anonymous) @ workbench.desktop.main.js:662
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:58
fire @ workbench.desktop.main.js:60
onViewPointer @ workbench.desktop.main.js:124
(anonymous) @ workbench.desktop.main.js:58
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:58
fire @ workbench.desktop.main.js:60
g @ workbench.desktop.main.js:60
```
- Windows: `%homepath%/.cloudmusic/err.log`
```
1621060673408 400
1622246083473 400
1622246112095 400
1623821249241 400
1624669079377 400
1624669341070 400
1624675002364 512
1624675004518 512
1624680402882 TypeError: Cannot read property 'map' of undefined
    at fc (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.7\dist\server.js:8:21634)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.7\dist\server.js:9:8289)
1625014290102 400
1625028553931 400
1625042507718 Error: getaddrinfo ENOTFOUND music.163.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'music.163.com',
  config: {
    url: 'https://music.163.com/weapi/feedback/weblog',
    method: 'post',
    data: 'params=O%2BxntZqzEzRt5p%2FKDRfywSqy4F3KPLNlgEoETe50lPS1acKf1%2BLQBMiQOQM2YT6oHtYCdrJ5r8vLYgcq4Ce7HPLeWKgPKI7VpDvzBoSKQP3Jyuf2QtM%2FXmXfn0SyzzrORyMs4tZntnVeOOcY7Tn50HTODTNUk16QLFdickQtY6kbq%2FKAgD36d1pY%2FUDU1c%2F1uVY0TxRPTBrfzYnIGTp9Tuaq0qPBMrxotvjkhBtExcuaSgBfNp7ILb%2FxU1r3T%2B2A%2FxJ%2FM0ZQu7%2FXbKMWq3actuPvtXH9jUI76E3GNyt%2FbzHh5D6toQm%2FIyy3FWwzJBamaoJWtub2p9rEIN1kAB1mm3n4NIO%2BHHsgedwN2ecKdvyzPfFUkhUnNvyAuLAtTteSnPTA9Czr6XPIcwgoVHDuWw%3D%3D&encSecKey=2c6e9fbfa42a2a76ee4f61fd2fe8daf50abca413b82efb4a7cff4f9c2f3f47359673c717aacd7833ec74896bd189abfdc8c5a7deb548c5e6849568d13f936258d573480b967edc663dca169d710365d820e4b0358055add36d366d57e000c65a4d99c3fd857e0e1e91f9371c88a3d8ed45e6ddbd16a5ed7fc9c94ef112514e8a',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      Cookie: '__remember_me=true; %20Max-Age=1296000; %20Expires=Sun%2C%2030%20May%202021%2006%3A37%3A52%20GMT; %20Path=%2F; __csrf=254c02f4af046dd4d8f2241b80a3979d; NMTID=00OWDfq7Q1fALyDbEXSkx093kU8SZ4AAAF5br7coQ; MUSIC_U=b251b8c6fbe3a3dbda602f876ede4f9830e82bed7171d49c7838b785afaa752833a649814e309366',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15',
      'Content-Length': 716
    },
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 0,
    withCredentials: true,
    adapter: [Function (anonymous)],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    httpAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      [Symbol(kCapture)]: false
    },
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: -50,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/weapi/feedback/weblog',
      method: 'POST',
      headers: [Object],
      agent: [Agent],
      agents: [Object],
      auth: undefined,
      hostname: 'music.163.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/weapi/feedback/weblog'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 716,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /weapi/feedback/weblog HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Cookie: __remember_me=true; %20Max-Age=1296000; %20Expires=Sun%2C%2030%20May%202021%2006%3A37%3A52%20GMT; %20Path=%2F; __csrf=254c02f4af046dd4d8f2241b80a3979d; NMTID=00OWDfq7Q1fALyDbEXSkx093kU8SZ4AAAF5br7coQ; MUSIC_U=b251b8c6fbe3a3dbda602f876ede4f9830e82bed7171d49c7838b785afaa752833a649814e309366\r\n' +
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15\r\n' +
        'Content-Length: 716\r\n' +
        'Host: music.163.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/weapi/feedback/weblog',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'music.163.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://music.163.com/weapi/feedback/weblog',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
1625100345220 400
1625104176980 400
1625190848788 400
1625191822043 400
1625271733186 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:9:8289)
1625271733189 400
1625295802196 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:9:8289)
1625295802242 400
1625456253437 400
1625456253465 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:9:8289)
1625613464172 400
1625613464183 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.8\dist\server.js:9:8289)
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
1625816718649 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.9\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.9\dist\server.js:9:8295)
1625816718659 400
1625816789342 400
1625877170485 TypeError: Cannot read property 'dailySongs' of null
    at ra (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.9\dist\server.js:8:6307)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (c:\Users\30732\.vscode\extensions\yxl.cloudmusic-8.3.9\dist\server.js:9:8295)
1625877170497 400
1625877442773 400
```

**Environment (Help->About)**
Paste the content in `Help->About`
粘贴`帮助->关于`中的内容
```
版本: 1.58.0 (user setup)
提交: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
日期: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by Tim-Fang** [comment]
PS: 因为网易云网页版更新 只能通过扫码登陆 所以现在我只能用vsc听歌((

**Comment by YXL76** [comment]
主要还是你的网络环境有问题吧
