### ISSUE TITLE
code-server不能播放

### ISSUE THREAD

**Issue by maxshiro** [YXL76/cloudmusic-vscode#520]
侧边账号一栏不显示头像,并且无法播放歌曲,一直显示加载中...
使用手机号登录.

系统: Centos7
远程控制系统: Windows10
codeserver版本: v3.11.0
安装方式: vsix安装

**Comment by YXL76** [comment]
有 `https` 吗？

**Comment by maxshiro** [comment]
> 有 `https` 吗？
无,草,我试试https

**Comment by YXL76** [comment]
以及，控制台的错误信息贴一下

**Comment by maxshiro** [comment]
> 以及，控制台的错误信息贴一下

开了https,控制台:

`[2021-08-03T14:32:10.213Z] info  code-server 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd
[2021-08-03T14:32:10.214Z] info  Using user-data-dir ~/.local/share/code-server
[2021-08-03T14:32:10.241Z] info  Using config file ~/.config/code-server/config.yaml
[2021-08-03T14:32:10.241Z] info  HTTP server listening on http://0.0.0.0:10240
[2021-08-03T14:32:10.241Z] info    - Authentication is enabled
[2021-08-03T14:32:10.241Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-08-03T14:32:10.241Z] info    - Using certificate for HTTPS: /www/server/panel/vhost/cert/code.axro.top/fullchain.pem
[2021-08-03T14:32:22.184Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:32:33.184Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
  ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
  ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2021-08-03T14:32:53.179Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:04.160Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:24.134Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:35.171Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)`

**Comment by maxshiro** [comment]
> 以及，控制台的错误信息贴一下

```
[2021-08-03T14:32:10.213Z] info  code-server 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd
[2021-08-03T14:32:10.214Z] info  Using user-data-dir ~/.local/share/code-server
[2021-08-03T14:32:10.241Z] info  Using config file ~/.config/code-server/config.yaml
[2021-08-03T14:32:10.241Z] info  HTTP server listening on http://0.0.0.0:10240
[2021-08-03T14:32:10.241Z] info    - Authentication is enabled
[2021-08-03T14:32:10.241Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-08-03T14:32:10.241Z] info    - Using certificate for HTTPS: /www/server/panel/vhost/cert/code.axro.top/fullchain.pem
[2021-08-03T14:32:22.184Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:32:33.184Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
  ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
  ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2021-08-03T14:32:53.179Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:04.160Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:24.134Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
[2021-08-03T14:33:35.171Z] error Unauthorized HttpError: Unauthorized
    at ensureAuthenticated (/usr/lib/code-server/out/node/http.js:38:15)
```

**Comment by YXL76** [comment]
浏览器的控制台，按`F12`

**Comment by maxshiro** [comment]
> 以及，控制台的错误信息贴一下

很怪,我用反向代理登进去以后白屏,啥也不显示

**Comment by maxshiro** [comment]
> 浏览器的控制台，按`F12`

![image](https://user-images.githubusercontent.com/20143941/128035257-0554d841-813d-49f4-b4d8-6efe4a63a36f.png)

**Comment by YXL76** [comment]
基本认为这是上游的问题（参见[mhutchie/vscode-git-graph#535](https://github.com/mhutchie/vscode-git-graph/issues/535#issuecomment-872193909)这条评论）。

当然，`https`也是需要的，`code-server`相关的 Issue：[#3757](https://github.com/cdr/code-server/discussions/3757)，[#3850](https://github.com/cdr/code-server/issues/3850)
