### ISSUE TITLE
可能由代理引起的无法登录

### ISSUE THREAD

**Issue by ADSWT518** [YXL76/cloudmusic-vscode#527]
自https://github.com/YXL76/cloudmusic-vscode/issues/439#issuecomment-894021690 继续讨论

**Describe the bug**
点击二维码登录时，没有反应。使用密码登录则直接出现“登录失败”的提示。在Windows下和arch Linux下均出现了此问题，但将`http_proxy`和`https_proxy`添加到环境变量之前，一切正常。（添加这两个环境变量主要是为了可以在终端使用代理从而加快下载速度）

**Error information**
![image](https://user-images.githubusercontent.com/58338486/128479152-5c124dc0-dea6-44f4-8f12-b1c6de9399b1.png)

**Server logs**
```
1628237405730 Error: Request failed with status code 400
    at ns.exports (c:\Users\ADSWT518\.vscode\extensions\yxl.cloudmusic-9.1.3\dist\server.js:1:5090)
    at os.exports (c:\Users\ADSWT518\.vscode\extensions\yxl.cloudmusic-9.1.3\dist\server.js:1:5262)
    at IncomingMessage.<anonymous> (c:\Users\ADSWT518\.vscode\extensions\yxl.cloudmusic-9.1.3\dist\server.js:6:12135)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Environment**
```
版本: 1.59.0 (system setup)
提交: 379476f0e13988d90fab105c5c19e7abc8b1dea8
日期: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by YXL76** [comment]
先看看代理软件的日志，流量有没有走到那里

**Comment by ADSWT518** [comment]
> 先看看代理软件的日志，流量有没有走到那里

我用的是qv2ray，点击“二维码登录”的时候，软件的日志是没有增加新记录的。

***

不过我目前是把环境变量中的http_proxy去掉了，采用了别的方式进行命令行代理。现在使用本插件一切正常 :joy:

**Comment by cheng-shuai** [comment]
对，我也遇到了，使用代理的时候无法登陆

**Comment by AlexXuCN** [comment]
我这边似乎也是，但是我既没有设置环境变量，也没有使用vsc设置里的http.proxy，但点击二维码登录时同样没有反应，使用密码/验证码登录则出现登录失败

**Comment by AlexXuCN** [comment]
> 我这边似乎也是，但是我既没有设置环境变量，也没有使用vsc设置里的http.proxy，但点击二维码登录时同样没有反应，使用密码/验证码登录则出现登录失败

err-9.2.4.log:
```
1633415572154 Error: write EPROTO 2290632:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633415821365 Error: write EPROTO 2290056:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633440694846 Error: write EPROTO 2290632:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633440786235 Error: write EPROTO 2280840:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633441007435 Error: write EPROTO 2280840:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633441216416 Error: write EPROTO 2290056:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633441484102 Error: write EPROTO 2290056:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
1633441504299 Error: write EPROTO 2290056:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

**Comment by YXL76** [comment]
> 我这边似乎也是，但是我既没有设置环境变量，也没有使用vsc设置里的http.proxy，但点击二维码登录时同样没有反应，使用密码/验证码登录则出现登录失败

在设置里关闭https
