### ISSUE TITLE
插件可能无法在Vscode for Web(CodeServer)里运行

### ISSUE THREAD

**Issue by 2659170494** [YXL76/cloudmusic-vscode#660]
**Describe the bug**
Vscode for Web是用Code-Server(Docker)搭建的。插件是通过Marketplace中的历史记录下载VSIX进行安装的，虽然插件可以正常安装，但是列表(除本地音乐库新建的文件夹外)全部为空，尝试使用Email或手机号登录账号时到输入密码环节Enter后无任何反应。在F12中看不到任何的记录，包括Docker中的容器日志也没有输出什么。想搜索歌曲时苦于找不到搜索框，看了Issue貌似要登录才可以搜索，且貌似作者把搜索框弄到了左下角的头像(我的Vscode For Web的头像框除了显示个Loading后什么反应都没有了)。请问这插件是否支持Vscode for web?

**Comment by 2659170494** [comment]
Log日志:
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libasound.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Function.init (/root/.local/share/code-server/extensions/yxl.cloudmusic-9.8.3/dist/server.js:15:3924)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/yxl.cloudmusic-9.8.3/dist/server.js:15:10487)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
(看起来找不到文件qwq，会不会是这个插件从一开始就已经停止了运行?如果是的话建议出错的时候务必加一个报错时弹出错误窗口)

**Comment by YXL76** [comment]
你的 Docker 环境没有音频库，用`wasm`模式吧

**Comment by 2659170494** [comment]
> 你的 Docker 环境没有音频库，用`wasm`模式吧
az,除此之外没有其它方案吗qwq?毕竟Code-server目前只支持nodejs和Docker环境qwq

**Comment by YXL76** [comment]
参考类似的描述 [run apps using audio in a docker container](https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container)

**Comment by 2659170494** [comment]
> 参考类似的描述 [run apps using audio in a docker container](https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container)

嗯谢谢答复，不过这个好像跟Code-Server不兼容qwq(文章中用的是TCP，但是Code-Server与浏览器之间的通讯用的是WebSocket)
