### ISSUE TITLE
不能播放歌曲，一直显示song: loading

### ISSUE THREAD

**Issue by xinyi-li7** [YXL76/cloudmusic-vscode#668]
**Describe the bug**
清楚简明地描述了该错误是什么。

无法播放歌曲，一直显示song: loading

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容
<img width="542" alt="image" src="https://user-images.githubusercontent.com/69008042/163251432-f8a9eb1a-dab9-4592-af09-3b9bdf987a88.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/69008042/163251457-3189c390-76d9-486f-918b-10888f00b1dc.png">

**Server logs**
Note: There may be sensitive content (e.g. cookies), please desensitize before pasting.
注意：其中可能有敏感内容（如 cookie），粘贴前请脱敏。
```
(node:11006) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
1649220535333 Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
1649220535412 Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
1649220535413 TypeError: Cannot read properties of undefined (reading 'data')
    at Object.Cm (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:15:2389)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ya (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:14:3705)
    at async Function.load (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:15:4996)
(node:11630) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:1479) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:3693) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:12088) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:11202) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
1649571651672 Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
(node:25804) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:1515) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:53850) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
1649819716054 Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
(node:84142) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
1649874848129 Error: timeout of 8000ms exceeded
    at qn.exports (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:2:5309)
    at re.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:11942)
    at re.emit (node:events:390:28)
    at re.emit (node:domain:475:12)
    at Timeout.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:2680)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
1649874856853 Error: timeout of 8000ms exceeded
    at qn.exports (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:2:5309)
    at re.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:11942)
    at re.emit (node:events:390:28)
    at re.emit (node:domain:475:12)
    at Timeout.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:2680)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
1649874865600 Error: timeout of 8000ms exceeded
    at qn.exports (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:2:5309)
    at re.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:11942)
    at re.emit (node:events:390:28)
    at re.emit (node:domain:475:12)
    at Timeout.<anonymous> (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:7:2680)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
....
1649876559759 Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
1649876668688 Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
1649876668689 Error
    at /Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:15:1766
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async di (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:15:1867)
    at async fm (/Users/xinyili/.vscode/extensions/yxl.cloudmusic-9.8.3-darwin-arm64/dist/server.js:14:21872)
(node:3156) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:3645) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)

```

- Linux/MacOS: `~/.cloudmusic/err-<version>.log`
- Windows: `%homepath%/.cloudmusic/err-<version>.log`

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

**Comment by YXL76** [comment]
可以尝试更换网络环境

**Comment by xinyi-li7** [comment]
刚刚重装了下vs code可以啦！

**Comment by xinyi-li7** [comment]
隔了好了几天又出现这个问题，会是因为缓存不够么？

**Comment by YXL76** [comment]
暂时没有什么好的解决方法

**Comment by xinyi-li7** [comment]
好的谢谢
