### ISSUE TITLE
native 播放模式下激活扩展报错

### ISSUE THREAD

**Issue by manlao** [YXL76/cloudmusic-vscode#706]
**Describe the bug**
在 native 播放模式下无法激活扩展（状态栏可显示，账号、歌单等无法显示，大部分按钮点击无反应）
切换至 wasm 播放模式可正常使用

**Error information**
控制台无报错

**Server logs**
2022-06-01T07:51:26.609Z Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    at Function.mediaSession (.vscode/extensions/yxl.cloudmusic-9.10.0-darwin-x64/dist/server.js:16:4373)
    at Function.init (.vscode/extensions/yxl.cloudmusic-9.10.0-darwin-x64/dist/server.js:16:4139)
    at .vscode/extensions/yxl.cloudmusic-9.10.0-darwin-x64/dist/server.js:16:10373
    at Object.<anonymous> (.vscode/extensions/yxl.cloudmusic-9.10.0-darwin-x64/dist/server.js:16:10755)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

**Environment**
版本: 1.67.2
提交: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
日期: 2022-05-17T18:20:57.384Z (2 周前)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

macOS 12.4

**Comment by manlao** [comment]
> 请问执行这个命令有用吗？
> 
> ```shell
> sudo chmod 755 ~/.vscode/extensions/yxl.cloudmusic-9.10.0-darwin-x64/build/darwin-x64-media
> ```

执行命令重启后可用

**Comment by manlao** [comment]
> OK，想问一下目前播放的音乐会出现在媒体中心吗？是否能用媒体键控制？

会出现，可以用媒体键控制

**Comment by manlao** [comment]
v9.10.1 darwin-x64-media 权限又变成了 644 @YXL76

**Comment by YXL76** [comment]
`v9.10.2` 修复了吗？

**Comment by manlao** [comment]
> `v9.10.2` 修复了吗？

v9.10.2 权限正常。效率真高，👍

btw: 感谢开发这么好用的扩展
