### ISSUE TITLE
GLIBC 2.28 not supported on Ubuntu 18.04

### ISSUE THREAD

**Issue by Eralien** [YXL76/cloudmusic-vscode#717]
**Describe the bug**
Hello, 我无法登录我的账户，无论是邮箱、手机、二维码等都不可以。查看`$HOME/.cloudmusic`下的问题，似乎是由于程序无法找到GLIBC 2.28版本的libc.so。由于我使用的系统是Ubuntu 18.04, 所以系统默认的libc.so是GLIB 2.27。

**Error information**
```txt
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: err-9.10.2.log
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 2022-06-14T02:08:38.452Z Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by $HOME
       │ /.vscode/extensions/yxl.cloudmusic-9.10.2-linux-x64/build/linux-x64.node)
   2   │     at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
   3   │     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
   4   │     at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
   5   │     at Module.load (node:internal/modules/cjs/loader:1035:32)
   6   │     at Module._load (node:internal/modules/cjs/loader:876:12)
   7   │     at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
   8   │     at Module.require (node:internal/modules/cjs/loader:1059:19)
   9   │     at require (node:internal/modules/cjs/helpers:102:18)
  10   │     at Function.init ($HOME/.vscode/extensions/yxl.cloudmusic-9.10.2-linux-x64/dist/server.js:16:3908)
  11   │     at $HOME/.vscode/extensions/yxl.cloudmusic-9.10.2-linux-x64/dist/server.js:16:10373
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Environment**
版本: 1.68.0
提交: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
日期: 2022-06-08T11:49:57.055Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-107-generic

**Comment by YXL76** [comment]
请检查 `v9.10.3`

**Comment by Eralien** [comment]
> 请检查 `v9.10.3`

可以正常登录了！非常感谢！
