### ISSUE TITLE
`GLIBC_2.25' not found

### ISSUE THREAD

**Issue by zfshennl** [YXL76/cloudmusic-vscode#727]
**Describe the bug**
无法通过邮箱，二维码登录。系统是Ubuntu 22.04，GLIBC 版本是 2.35。

**Error information**
![Screenshot from 2022-06-20 13-51-46](https://user-images.githubusercontent.com/91741901/174595760-914e54d9-2563-40e7-b464-6a12775f2eec.png)

**Server logs**
2022-06-20T11:51:11.044Z Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by $HOME/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/build/linux-x64.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.init (file://$HOME/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/dist/server.mjs:16:3964)
    at file://$HOME/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/dist/server.mjs:16:10421

**Environment**
版本 1.68.1
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.0-39-generic snap

**Comment by YXL76** [comment]
VS Code 是用 Snap 安装的吗？可以试试用 apt 安装

**Comment by zfshennl** [comment]
原先确实是snap安装的，在使用apt重新安装后问题已解决，感谢!
