### ISSUE TITLE
不能登录呀

### ISSUE THREAD

**Issue by CK-AK** [YXL76/cloudmusic-vscode#734]
系统版本：ubuntu1804
vscode版本：1.68.1
Cloudmusic版本：9.10.5
问题描述：
登录不了；
用邮箱登录，输入密码之后按回车键没反应
用二维码登录，点了二维码选项之后，没有二维码出现

总之，就是登不上去

**Comment by YXL76** [comment]
日志: `~/.cloudmusic/err-<version>.log`

**Comment by CK-AK** [comment]
2022-06-27T08:42:34.708Z Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/k/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/build/linux-x64.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.init (file:///home/k/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/dist/server.mjs:16:3964)
    at file:///home/k/.vscode/extensions/yxl.cloudmusic-9.10.5-linux-x64/dist/server.mjs:16:10421

**Comment by YXL76** [comment]
同 #727
