### ISSUE TITLE
歌曲数目多导致quene出现异常

### ISSUE THREAD

**Issue by ZiyueC** [YXL76/cloudmusic-vscode#783]
**Describe the bug**
清楚简明地描述了该错误是什么。

playlist里的歌曲如果数量较多并加入quene播放，会导致滚轮滑动不流畅，shuffle之后还会出现bug

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

![image](https://user-images.githubusercontent.com/23124524/184072583-d72d236e-1e90-49ce-bb3b-cb8cebab5e9a.png)
![image](https://user-images.githubusercontent.com/23124524/184072762-155ddf8c-8dba-4c5e-aec1-7ccb2faa6d7e.png)

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

"2022-08-10T03:48:16.285Z undefined
2022-08-10T03:52:04.966Z undefined
2022-08-10T03:52:35.181Z undefined
2022-08-10T06:46:59.320Z TypeError: failed to downcast any to string
    at Function.load (file:///c:/Users/chenzy/.vscode/extensions/yxl.cloudmusic-9.13.3-win32-x64/dist/server.mjs:18:5347)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-10T07:03:20.806Z RequestError: socket hang up
    at ClientRequest.<anonymous> (file:///c:/Users/chenzy/.vscode/extensions/yxl.cloudmusic-9.13.3-win32-x64/dist/server.mjs:17:38547)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketOnEnd (node:_http_client:471:9)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at connResetException (node:internal/errors:691:14)
    at Socket.socketOnEnd (node:_http_client:471:23)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-08-10T07:05:51.281Z Error: EPERM: operation not permitted, stat 'C:\Users\chenzy\.cloudmusic\tmp\1296548180'
2022-08-10T07:07:51.288Z Error: EPERM: operation not permitted, stat 'C:\Users\chenzy\.cloudmusic\tmp\1296548180'
2022-08-10T07:31:55.740Z TypeError: failed to downcast any to string
    at Function.load (file:///c:/Users/chenzy/.vscode/extensions/yxl.cloudmusic-9.13.3-win32-x64/dist/server.mjs:18:5347)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-10T07:32:06.155Z TypeError: failed to downcast any to string
    at Function.load (file:///c:/Users/chenzy/.vscode/extensions/yxl.cloudmusic-9.13.3-win32-x64/dist/server.mjs:18:5347)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
"

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
![image](https://user-images.githubusercontent.com/23124524/184072795-f616e0cf-7e99-4121-b154-71c1f597af41.png)

**Comment by YXL76** [comment]
歌曲数目大概是多少呢

**Comment by ZiyueC** [comment]
440首左右，不能确定是因为数目太多导致这样的问题。

兰陈昕 ***@***.***> 于 2022年8月11日周四 20:04写道：

**Comment by YXL76** [comment]
认为是VS Code 的渲染问题，可能关联 https://github.com/microsoft/vscode/issues/110450

**Comment by YXL76** [comment]
这种现象经常出现吗？还要排除是否受到其他拓展的影响 @ZiyueC

**Comment by ZiyueC** [comment]
经过测试应该是由于歌单里加入了 从云盘导入的歌 造成的，就是先本地下载音乐然后上传云盘，再添加进歌单，会导致滚动出现bug
