### ISSUE TITLE
无法播放本地音乐

### ISSUE THREAD

**Issue by linyuansup** [YXL76/cloudmusic-vscode#807]
**Describe the bug**
清楚简明地描述了该错误是什么。

在播放本地音乐时一直加载中
![image](https://user-images.githubusercontent.com/49548096/188671363-937c1549-6241-45be-a524-39838d83f4aa.png)
![image](https://user-images.githubusercontent.com/49548096/188671406-70269ead-357f-492d-b96e-6563b183d86e.png)

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。
workbench.desktop.main.js:sourcemap:603  WARN [twxs.cmake]: 无法注册“cmake.cmakePath”。此属性已注册。
workbench.desktop.main.js:sourcemap:2127 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///c%3A/Users/93601/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///c%3A/Users/93601/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.embedded.macro.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2127
workbench.desktop.main.js:sourcemap:2127 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/93601/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/93601/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2127
workbench.desktop.main.js:sourcemap:87 [Extension Host] filesize is active
workbench.desktop.main.js:sourcemap:87 [Extension Host] Server: {
  "Commands": [
    "gopls.add_dependency",
    "gopls.add_import",
    "gopls.apply_fix",
    "gopls.check_upgrades",
    "gopls.edit_go_directive",
    "gopls.gc_details",
    "gopls.generate",
    "gopls.generate_gopls_mod",
    "gopls.go_get_package",
    "gopls.list_imports",
    "gopls.list_known_packages",
    "gopls.regenerate_cgo",
    "gopls.remove_dependency",
    "gopls.run_tests",
    "gopls.run_vulncheck_exp",
    "gopls.start_debugging",
    "gopls.test",
    "gopls.tidy",
    "gopls.toggle_gc_details",
    "gopls.update_go_sum",
    "gopls.upgrade_dependency",
    "gopls.vendor"
  ],
  "Name": "gopls",
  "Version": "v0.9.4",
  "GoVersion": "go1.19"
}
workbench.desktop.main.js:sourcemap:87 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:87 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:603   ERR ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers': Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
workbench.desktop.main.js:sourcemap:87 [Extension Host] [WakaTime][WARN] Failed to download https://github.com/wakatime/wakatime-cli/releases/download/v1.54.0/wakatime-cli-windows-amd64.zip
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:87 [Extension Host] [WakaTime][WARN] Error: connect ETIMEDOUT 13.114.40.48:443
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:87 [Extension Host] Cloudmusic: wasm mode.
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.16.2server
workbench.desktop.main.js:sourcemap:87 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.16.2server
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.16.2bc-server
workbench.desktop.main.js:sourcemap:87 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.16.2bc-server
y @ workbench.desktop.main.js:sourcemap:87
provider.js:1 Audio Player: HTMLAudioElement
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] (node:40048) Warning: Closing file descriptor 7 on garbage collection
(Use `Code --trace-warnings ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:87 [Extension Host] (node:40048) Warning: Closing file descriptor 7 on garbage collection
(Use `Code --trace-warnings ...` to show where the warning was created)
y @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] (node:40048) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
workbench.desktop.main.js:sourcemap:87 [Extension Host] (node:40048) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
y @ workbench.desktop.main.js:sourcemap:87
file+.vscode-resource.vscode-cdn.net/c%3A/Users/93601/Music/%E4%B8%87%E8%B1%A1%E9%9C%9C%E5%A4%A9.flac:1          Failed to load resource: the server responded with a status of 401 ()
provider.js:1 MediaImage src can only be of http/https/data/blob scheme: vscode-webview://02tsg526iu4uk4hokr9jmjj2b5f6vulor2a4ckk5krhnplbcla1b/index.html?id=1cb6783d-95f6-4696-aa4d-4a85327e77b6&origin=df4a13e9-6f65-40f3-a91f-53dc0c168f79&swVersion=4&extensionId=YXL.cloudmusic&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=webviewView
i @ provider.js:1
file+.vscode-resource.vscode-cdn.net/c%3A/Users/93601/Music/%E4%B8%8D%E8%B5%B4.wav:1          Failed to load resource: the server responded with a status of 401 ()

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

2022-09-06T14:58:54.602Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8550)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:58:54.603Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8594)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:58:54.603Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8594)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:58:54.605Z Error: listen EADDRINUSE: address already in use \\.\pipe\tmp-cm-vsc-9.16.2server
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at $.init (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8168)
    at async Promise.all (index 0)
2022-09-06T14:58:54.605Z Error: listen EADDRINUSE: address already in use \\.\pipe\tmp-cm-vsc-9.16.2bc-server
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at jt.init (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:10063)
    at async Promise.all (index 1)
2022-09-06T14:59:33.213Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8550)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:59:33.215Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8550)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:59:33.216Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8594)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T14:59:33.220Z Error: listen EADDRINUSE: address already in use \\.\pipe\tmp-cm-vsc-9.16.2server
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at $.init (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8168)
    at async Promise.all (index 0)
2022-09-06T14:59:33.221Z Error: listen EADDRINUSE: address already in use \\.\pipe\tmp-cm-vsc-9.16.2bc-server
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at jt.init (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:10063)
    at async Promise.all (index 1)
2022-09-06T15:00:54.611Z Error: ENOENT: no such file or directory, scandir 'C:\Users\93601\.cloudmusic\tmp'
2022-09-06T15:01:33.243Z Error: ENOENT: no such file or directory, scandir 'C:\Users\93601\.cloudmusic\tmp'
2022-09-06T15:02:54.621Z Error: ENOENT: no such file or directory, scandir 'C:\Users\93601\.cloudmusic\tmp'
2022-09-06T15:03:33.244Z Error: ENOENT: no such file or directory, scandir 'C:\Users\93601\.cloudmusic\tmp'
2022-09-06T15:14:28.228Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8594)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T15:14:28.229Z Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at $.send (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8300)
    at $._setMaster (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:8594)
    at Server.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:7893)
2022-09-06T15:14:28.230Z Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:474:14)
    at jt._broadcast (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:10226)
    at Socket.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:9963)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2022-09-06T15:14:28.231Z Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:474:14)
    at jt._broadcast (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:10226)
    at Socket.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.2-win32-x64/dist/server.mjs:36:9963)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
![image](https://user-images.githubusercontent.com/49548096/188672135-93f09c73-6739-4812-86d2-327cdc037d8f.png)

**Comment by linyuansup** [comment]
bug仍存在qaq而且日志空了

**Comment by YXL76** [comment]
请检查`v9.16.4`

**Comment by linyuansup** [comment]
perfect！
感谢感谢ww

**Comment by linyuansup** [comment]
又出现了qaq，还是没有log
 WARN Settings pattern "keyboard.*" doesn't match any settings
log.ts:307  WARN [twxs.cmake]: 无法注册“cmake.cmakePath”。此属性已注册。
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///c%3A/Users/93601/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///c%3A/Users/93601/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.embedded.macro.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/93601/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/93601/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings
console.ts:137 [Extension Host] filesize is active
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
y @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
y @ console.ts:137
log.ts:313   ERR ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers': Error: ENOENT: no such file or directory, open 'c:\Users\93601\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings
console.ts:137 [Extension Host] Server: {
  "Commands": [
    "gopls.add_dependency",
    "gopls.add_import",
    "gopls.apply_fix",
    "gopls.check_upgrades",
    "gopls.edit_go_directive",
    "gopls.gc_details",
    "gopls.generate",
    "gopls.generate_gopls_mod",
    "gopls.go_get_package",
    "gopls.list_imports",
    "gopls.list_known_packages",
    "gopls.regenerate_cgo",
    "gopls.remove_dependency",
    "gopls.run_tests",
    "gopls.run_vulncheck_exp",
    "gopls.start_debugging",
    "gopls.test",
    "gopls.tidy",
    "gopls.toggle_gc_details",
    "gopls.update_go_sum",
    "gopls.upgrade_dependency",
    "gopls.vendor"
  ],
  "Name": "gopls",
  "Version": "v0.9.4",
  "GoVersion": "go1.19"
}
console.ts:137 [Extension Host] Cloudmusic: wasm mode.
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings

**Comment by YXL76** [comment]
log 里没有有用信息，把其他拓展先禁用了吧，顺便提供一下文件的路径

**Comment by linyuansup** [comment]
禁用除语言包外所以扩展还是不行qaq
路径 `C:\User\93601\OneDrive`，确定所有 OneDrive 文件已同步至本机

**Comment by linyuansup** [comment]
2022-09-07T12:14:32.076Z HTTPError: Response code 502 (Bad Gateway)
    at Oe._onResponseBase (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.4-win32-x64/dist/server.mjs:35:37680)
    at Oe._onResponse (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.4-win32-x64/dist/server.mjs:35:38326)
    at ClientRequest.<anonymous> (file:///c:/Users/93601/.vscode/extensions/yxl.cloudmusic-9.16.4-win32-x64/dist/server.mjs:35:38566)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:538:35)
    at ClientRequest.emit (node:domain:475:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:482:22)
    at Socket.emit (node:events:526:28)

刚出的日志，然后我把网易云账号退出重新登录了一下，又可以了hh
但本地似乎不应该和联网有关（xxxx

**Comment by YXL76** [comment]
下次看一下是单曲不能播放还是都不行，也可能是和文件有关

**Comment by YXL76** [comment]
合并至 #813

**Comment by linyuansup** [comment]
今天再次发生了，同样是没有任何日志，本地和联网均不能播放
但是我把网易云账号退掉之后，本地就正常了（甚至连code都没有重启）

**Comment by linyuansup** [comment]
而且似乎不是 #813 的问题
