### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by GuoXiaoyang** [YXL76/cloudmusic-vscode#850]
**Describe the bug**
插件 Tab 无法登录，也没有加载状态，日志有报错；尝试卸载再安装，依旧存在问题
<img width="343" alt="image" src="https://user-images.githubusercontent.com/8994590/202990601-5fd1fa2d-26b2-4c60-932c-e2454f5aae9d.png">

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。
```
workbench.desktop.main.js:87 [Extension Host] TypeError: Cannot read properties of undefined (reading 'uid')
    at /Users/guoxiaoyang/.vscode/extensions/yxl.cloudmusic-9.17.0-darwin-arm64/dist/extension.js:77:450
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ge.#a (/Users/guoxiaoyang/.vscode/extensions/yxl.cloudmusic-9.17.0-darwin-arm64/dist/extension.js:44:8348)
E @ workbench.desktop.main.js:87
$logExtensionHostMessage @ workbench.desktop.main.js:1743
_doInvokeHandler @ workbench.desktop.main.js:1743
_invokeHandler @ workbench.desktop.main.js:1743
_receiveRequest @ workbench.desktop.main.js:1743
_receiveOneMessage @ workbench.desktop.main.js:1743
(anonymous) @ workbench.desktop.main.js:1743
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:546
_receiveMessage @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
y @ workbench.desktop.main.js:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
```

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。
```
2022-11-21T07:25:53.349Z TypeError: Cannot read properties of null (reading 'userId')
    at Ys (file:///Users/guoxiaoyang/.vscode/extensions/yxl.cloudmusic-9.17.0-darwin-arm64/dist/server.mjs:35:6364)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:22:48.959Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
macOS: Ventura 13.0.1
```

**Comment by GuoXiaoyang** [comment]
嗯，看起来是被退出了，用另外一种方式登录进来了
