### ISSUE TITLE
无法播放某首特定音乐

### ISSUE THREAD

**Issue by AZ-201** [YXL76/cloudmusic-vscode#858]
**Describe the bug**
新从云盘中喜欢了一首音乐，但是播放歌单会直接跳过

**Error information**
```
 ERR TypeError: Cannot read properties of null (reading 'value')
    at v (markdownRenderer.ts:446:23)
    at Dc.getHover (treeView.ts:982:91)
    at Dc.renderElement (treeView.ts:1026:22)
    at s.renderElement (asyncDataTree.ts:108:17)
    at _.renderElement (abstractTree.ts:414:17)
    at $.renderElement (listWidget.ts:1125:13)
    at a.insertItemInDOM (listView.ts:815:13)
    at a._splice (listView.ts:565:10)
    at a.splice (listView.ts:467:16)
    at splice.ts:17:35
    at Array.forEach (<anonymous>)
    at t.splice (splice.ts:17:20)
    at listWidget.ts:1446:57
    at m.bufferEvents (event.ts:1115:13)
    at H.splice (listWidget.ts:1446:22)
    at H.splice (abstractTree.ts:1270:9)
    at C.spliceSimple (indexTreeModel.ts:305:14)
    at C.splice (indexTreeModel.ts:156:9)
    at R._setChildren (objectTreeModel.ts:122:14)
    at R.setChildren (objectTreeModel.ts:71:8)
    at I.setChildren (objectTree.ts:63:14)
    at ce.render (asyncDataTree.ts:968:13)
    at ce.refreshAndRenderNode (asyncDataTree.ts:729:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ce._updateChildren (asyncDataTree.ts:520:3)
    at async ce.updateChildren (asyncDataTree.ts:506:3)
    at async Promise.all (index 0)
    at async de.doRefresh (treeView.ts:804:5)
```

**Server logs**
```
2022-12-01T08:23:13.197Z Error: ENOENT: no such file or directory, open 'C:\Users\name\.cloudmusic\retain'
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
2022-12-06T06:36:46.543Z Error: Failed to load C:\Users\name\.cloudmusic\cache\music\videoplayback-1944705108
    at oa._load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:13435)
    at oa.load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:11278)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-07T03:23:20.755Z Error: Failed to load C:\Users\name\.cloudmusic\cache\music\Hello,world!-31311449
    at oa._load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:13435)
    at oa.load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:11278)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-08T11:20:08.803Z Error: Failed to load C:\Users\cuiweihang\.cloudmusic\tmp\1461035030
    at oa._load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:13435)
    at oa.load (file:///c:/Users/name/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:35:11278)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-08T11:20:45.753Z { code: 400 }
2022-12-08T11:20:47.156Z { code: 400 }

```
**Environment**
```
版本: 1.70.2 (system setup)
提交: e4503b30fc78200f846c62cf8091b76ff5547662
日期: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by YXL76** [comment]
不在网易云曲库中的歌曲？
