### ISSUE TITLE
疑似在1.74.0版本的VSCode下会导致磁盘极大占用

### ISSUE THREAD

**Issue by ws2bhhh** [YXL76/cloudmusic-vscode#860]
**Describe the bug**
清楚简明地描述了该错误是什么。
无法播放音乐的同时挂机一段时间后blob_storage暴增到50G左右
**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。
尝试重启VSCode后解决故没有截图
**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。
…
2022-12-10T15:04:08.487Z RequestError: New streams cannot be created after receiving a GOAWAY
    at us.<anonymous> (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:33:38611)
    at Object.onceWrapper (node:events:646:26)
    at us.emit (node:events:538:35)
    at us.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at new NodeError (node:internal/errors:371:5)
    at ClientHttp2Session.request (node:internal/http2/core:1722:13)
    at g.request (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:42930)
    at Object.resolve (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:43534)
    at $e._accept (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:39468)
    at file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:40299
    at new Promise (<anonymous>)
    at $e.getSession (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:39570)
    at file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:43484
    at new Promise (<anonymous>)
2022-12-10T15:04:43.621Z RequestError: Stream closed with error code NGHTTP2_REFUSED_STREAM
    at us.<anonymous> (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:33:38611)
    at Object.onceWrapper (node:events:646:26)
    at us.emit (node:events:538:35)
    at us.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at new NodeError (node:internal/errors:371:5)
    at ClientHttp2Stream._destroy [as __destroy] (node:internal/http2/core:2330:13)
    at t._destroy (file:///c:/Users/X/.vscode/extensions/yxl.cloudmusic-9.17.0-win32-x64/dist/server.mjs:2:36973)
    at _destroy (node:internal/streams/destroy:102:25)
    at ClientHttp2Stream.destroy (node:internal/streams/destroy:64:5)
    at Http2Stream.onStreamClose (node:internal/http2/core:544:12)
(node:14924) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `Code --trace-warnings ...` to show where the warning was created)
…
**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
版本: 1.74.0 (system setup)
提交: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
日期: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
沙盒化: No

**Comment by ws2bhhh** [comment]
文件夹位置位于：
C:\Users\X\AppData\Roaming\Code\blob_storage
在播放本地缓存曲目持续失败后大小暴增磁盘占用率打满，可以复现

**Comment by YXL76** [comment]
写入磁盘应该属于正常情况（[Chrome's Blob Storage System Design](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md#summary-terminology)），需要关注的是 GC 没被调起还是有内存泄漏

**Comment by ws2bhhh** [comment]
> 写入磁盘应该属于正常情况（[Chrome's Blob Storage System Design](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md#summary-terminology)），需要关注的是 GC 没被调起还是有内存泄漏

不是很懂。。。这个是大文件缓存？不过目前版本这个问题已经不再出现；现在正常播放时**blob_storage目录大小为0**，不论切歌还是更换播放列表都没有变化
