### ISSUE TITLE
无法播放或者下载特定音乐

### ISSUE THREAD

**Issue by Misaka19327** [YXL76/cloudmusic-vscode#864]
我喜欢的歌单里有一首，轮到的时候会直接跳过，这首歌能进详情页面，但是也无法下载。
报错信息：
2022-12-18T02:06:44.546Z Error
    at Zs.oa [as _getPath] (file:///c:/Users/30903/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:36:3586)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Zs.load (file:///c:/Users/30903/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:35:11265)

这个报错信息会在要播放这首歌的时候出现，下载没有报错。

**Comment by YXL76** [comment]
方便贴一下歌曲链接吗？

**Comment by Misaka19327** [comment]
抱歉 贴链接的时候才发现这是vip的 手机上是精简过的网易云所以收藏的时候没发现这个事情 非常抱歉
