### ISSUE TITLE
播放意外终止

### ISSUE THREAD

**Issue by YuLun-bili** [YXL76/cloudmusic-vscode#868]
添加音乐至播放列表后无法播放音乐，但是其信息可以正常显示

Error Info:
```
workbench.desktop.main.js:616  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
workbench.desktop.main.js:89 [Extension Host] Git installation not found.
E @ workbench.desktop.main.js:89
workbench.desktop.main.js:616  INFO [perf] Render performance baseline is 74ms

... (workbench.desktop.main.js:605 [lua]: (lua errors/warnings) S @ workbench.desktop.main.js:605)

workbench.desktop.main.js:89 [Extension Host] Cloudmusic: native mode.
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

Log:
```
2022-12-13T17:07:26.852Z 请勿重复签到
2022-12-18T13:46:02.641Z { code: -2, msg: '重复签到' }
2022-12-18T19:33:05.032Z { code: -2, msg: '重复签到' }
2022-12-20T17:21:54.391Z 请勿重复签到
2022-12-21T16:31:41.142Z 请勿重复签到
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\268ddda\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-12-21T17:00:49.138Z Error: EPERM: operation not permitted, stat 'C:\Users\Anson\.cloudmusic\tmp\426027665'
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\268ddda\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-12-21T18:22:45.794Z Error: Failed to load C:\Users\Anson\.cloudmusic\cache\music\Microburst-426027665
    at ea._load (file:///c:/Users/Anson/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:35:13480)
    at ea.load (file:///c:/Users/Anson/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:35:11323)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
*不同歌曲的加载错误是一致的，这里只放一个
VScode:
```
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by YuLun-bili** [comment]
更新：昨天晚上关机后今天打开VScode正常了一阵又不播放了

Error Info:
```
workbench.desktop.main.js:sourcemap:616  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
workbench.desktop.main.js:sourcemap:616  INFO [perf] Render performance baseline is 32ms
workbench.desktop.main.js:sourcemap:89 [Extension Host] Git installation not found.
E @ workbench.desktop.main.js:sourcemap:89

... (workbench.desktop.main.js:sourcemap:605 [lua]: (lua errors/warnings) S @ workbench.desktop.main.js:sourcemap:605)

workbench.desktop.main.js:sourcemap:89 [Extension Host] Cloudmusic: native mode.
workbench.desktop.main.js:sourcemap:616   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
workbench.desktop.main.js:sourcemap:89 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
E @ workbench.desktop.main.js:sourcemap:89
workbench.desktop.main.js:sourcemap:616   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
workbench.desktop.main.js:sourcemap:89 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
E @ workbench.desktop.main.js:sourcemap:89
```
Log:
```
2022-12-22T12:47:47.745Z RequestError: Stream closed with error code NGHTTP2_REFUSED_STREAM
    at ns.<anonymous> (file:///c:/Users/Anson/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:33:43755)
    at Object.onceWrapper (node:events:646:26)
    at ns.emit (node:events:538:35)
    at ns.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at new NodeError (node:internal/errors:371:5)
    at ClientHttp2Stream._destroy [as __destroy] (node:internal/http2/core:2330:13)
    at t._destroy (file:///c:/Users/Anson/.vscode/extensions/yxl.cloudmusic-9.17.1-win32-x64/dist/server.mjs:2:32230)
    at _destroy (node:internal/streams/destroy:102:25)
    at ClientHttp2Stream.destroy (node:internal/streams/destroy:64:5)
    at Http2Stream.onStreamClose (node:internal/http2/core:544:12)
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\268ddda\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by YuLun-bili** [comment]
更新：
现在基本可以确定这个问题大概是队列意外为空导致，但是不清楚为何会触发。有时候听几个小时都没问题，脸黑的话听3首歌就报错

初步猜测是内存相关问题导致的队列意外清空。

此错误发生后计算机性能信息（任务管理器）
CPU：
![image](https://user-images.githubusercontent.com/70589524/213265752-46508acc-589f-4f9a-9c55-30edbc66eb21.png)
内存：
![image](https://user-images.githubusercontent.com/70589524/213265833-e8dd5dec-b790-4543-97d5-fc3a2d71f3d0.png)
* 32G 内存为：8GB实体+24GB虚拟（8192MB-16384MB，位于C盘；16384MB-65536MB，位于D盘）


日志：
```
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\268ddda\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
错误信息：
```
console.ts:137 [Extension Host] Cloudmusic: native mode.
log.ts:316   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
console.ts:137 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
E @ console.ts:137
log.ts:316   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
console.ts:137 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
E @ console.ts:137
log.ts:304  INFO [perf] Render performance baseline is 36ms
log.ts:316   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
console.ts:137 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1server
E @ console.ts:137
log.ts:316   ERR [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
console.ts:137 [Extension Host] connect ENOENT \\.\pipe\tmp-cm-vsc-9.17.1bc-server
E @ console.ts:137
```

**Comment by aquawius** [comment]
我也遇到了相同的问题, 切换歌曲有些时候就没有声音了, 但是歌词等信息显示正常
