### ISSUE TITLE
无法登录 - 找不到要与此 MediaPlaybackControl 实例关联的相应视图。请确保已初始化视图

### ISSUE THREAD

**Issue by lawgeorge202** [YXL76/cloudmusic-vscode#909]
**Describe the bug**
无法登录，点击各个登录选项均无反应

**Server logs**

Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: Error(Error { code: 0x80070578, message: 找不到要与此 MediaPlaybackControl 实例关联的相应视图。请确保已初始化视图。 })
    at new ea (file:///c:/Users/Bookman/.vscode/extensions/yxl.cloudmusic-9.18.0-win32-x64/dist/server.mjs:35:12579)
    at file:///c:/Users/Bookman/.vscode/extensions/yxl.cloudmusic-9.18.0-win32-x64/dist/server.mjs:35:13811
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

**Environment**
win 8.1
vscode 1.75
cloudmusic 9.18

**Comment by YXL76** [comment]
试一下`v9.19.0`

**Comment by ulpyuxa** [comment]
我这边v9.19.0放着音乐，放个几首或者10来首音乐
就不放了，
就再也不放了，
就真的再也不放了，
除非重启电脑。
