### ISSUE TITLE
私人FM播放一段时间后没有声音

### ISSUE THREAD

**Issue by Vi-brance** [YXL76/cloudmusic-vscode#915]
**Describe the bug**
在播放`私人FM`时，若干首歌结束后，下一首歌没有声音，界面显示正在播放，切换播放设备和暂停重播都不管用，只有关闭vscode并清理相关后台进程再重启才能恢复。

**Error information**
```
connect ENOENT \\.\pipe\tmp-cm-vsc-9.19.0bc-server
T @ workbench.desktop.main.js:90
```
> ps：由于还有其他插件运行，所以我不确定该信息是否是`cloudmusic`的异常信息

**Server logs**
```
2023-03-20T01:30:53.452Z Error: ENOENT: no such file or directory, open 'C:\Users\vi_br\.cloudmusic\retain'
2023-03-20T03:16:33.086Z Error: ENOENT: no such file or directory, open 'C:\Users\vi_br\.cloudmusic\retain'
2023-03-20T03:46:46.262Z Error: ENOENT: no such file or directory, open 'C:\Users\vi_br\.cloudmusic\retain'
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\d5b9ae3\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\d5b9ae3\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'cpal_wasapi_out' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\git\checkouts\rodio-6458f6e95b054746\d5b9ae3\src\decoder\symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Environment**
```
版本: 1.76.2 (user setup)
提交: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
日期: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: No
```

**Comment by YXL76** [comment]
同 #868，等待 https://github.com/RustAudio/rodio/pull/487
