### ISSUE TITLE
电脑休眠一段时间后重新点击播放键没有声音

### ISSUE THREAD

**Issue by jnw1** [YXL76/cloudmusic-vscode#922]
**Describe the bug**
清楚简明地描述了该错误是什么。

电脑休眠一段时间后，重新在vscode中点击播放键，除了没有声音外一切正常。歌词一直在往前走，只是没有声音（扩展中途并未关闭）
只能重启vscode解决。

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

ERROR: The process with PID 63452 (child process of PID 13144) could not be terminated.Reason: The operation attempted is not supported.
ERROR: The process with PID 53052 (child process of PID 13144) could not be terminated.Reason: There is no running instance of the task.
ERROR: The process with PID 13144 (child process of PID 67616) could not be terminated.Reason: There is no running instance of the task.
ERROR: The process "63920" not found.ERROR: The process "71120" not found.ERROR: The process "29960" not found.ERROR: The process "48356" not found.ERROR: The process "54904" not found.ERROR: The process "44192" not found.

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

2023-04-21T08:00:56.625Z Error: ENOENT: no such file or directory, open 'C:\Users\jnw1\.cloudmusic\retain'
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
2023-04-21T09:08:22.336Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
2023-04-21T09:08:29.420Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
2023-04-22T12:22:03.264Z Error: EPERM: operation not permitted, stat 'C:\Users\jnw1\.cloudmusic\tmp\35848938'
2023-04-24T09:44:39.896Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
2023-04-24T09:44:43.099Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
2023-04-24T09:44:46.757Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
2023-04-24T09:44:46.927Z Error: EPERM: operation not permitted, open 'C:\Users\jnw1\.cloudmusic\tmp\29263917'
2023-04-24T09:44:56.644Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)
2023-04-24T09:44:56.835Z Error: EPERM: operation not permitted, open 'C:\Users\jnw1\.cloudmusic\tmp\29263917'
2023-04-24T09:46:06.939Z RequestError: Timeout awaiting 'request' for 80000ms
    at ClientRequest.<anonymous> (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:33:43690)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:538:35)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.l [as _onTimeout] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:33:3661)
    at listOnTimeout (node:internal/timers:561:11)
    at process.processTimers (node:internal/timers:502:7)
2023-04-24T09:46:16.846Z RequestError: Timeout awaiting 'request' for 80000ms
    at ClientRequest.<anonymous> (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:33:43690)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:538:35)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.l [as _onTimeout] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:33:3661)
    at listOnTimeout (node:internal/timers:561:11)
    at process.processTimers (node:internal/timers:502:7)
2023-04-27T08:35:52.689Z Error
    at oa (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3709)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-04-27T12:55:03.349Z Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
2023-04-27T13:49:59.517Z Error
    at oa (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3709)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
an error occurred on output stream: The requested device is no longer available. For example, it has been unplugged.
2023-04-28T09:24:26.828Z Error
    at ea.Il [as _getPath] (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/jnw1/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by YXL76** [comment]
日志里的日期都有这些问题吗？还是只有28号。

**Comment by jnw1** [comment]
> 日志里的日期都有这些问题吗？还是只有28号。
自从使用以来一直都有这个问题。

**Comment by jnw1** [comment]
> 日志里的日期都有这些问题吗？还是只有28号。

自从使用以来一直都有这个问题。

**Comment by YXL76** [comment]
我没仔细研究，现阶段可能解决不了 https://github.com/RustAudio/rodio/issues/465
